### ISSUE TITLE
CR001: STT UI display length and inference length don't match

### ISSUE THREAD

**Issue by kaldan007** [OpenPecha/monlamai-app-web#209]
### Description
When recording audio up to the maximum allowed limit, the system fails to process the data correctly, leading to unexpected behavior. This issue needs to be resolved.

### Implementation plan
Investigate and debug the code to ensure audio chunks are properly captured and processed when the recording auto-submits at the time limit.

### Subtask

- [x] Capture audio chuck.

**Comment by Tendolls** [comment]
Fix Speech-to-Text Time Limit Error & Improve User Experience

**Feature:**
Enhance Speech-to-Text Functionality to Handle Time Limits

**Story:**
**As a** user, **I want** to be notified when my speech recording is approaching the 2-minute limit, and I want the app to automatically process my recording if the limit is exceeded, **so I** don't lose my entire recording or encounter a server error.

Tasks:
**Time Limit Notification:**
Implement a warning system that notifies users when they are nearing the 2-minute recording limit (e.g., at 1:45).
Display a visual cue or sound alert when the time is close to expiring.

**Automatic Translation Upon Time Limit Exceeding:**
Modify the system to automatically process and translate the recording as soon as the 2-minute limit is reached, even if the user does not press the stop button.
Ensure no loss of data when the time exceeds the limit; the recorded audio should seamlessly transition into translation mode.

**User Interface Update:**
Add a countdown timer during the recording process, showing how much time remains until the 2-minute limit.
Display a clear message to inform the user that the recording is being processed once the time limit is exceeded.

**Error Handling**
Ensure that no server errors occur due to the time limit being exceeded. Handle such situations smoothly by saving and processing the audio.

**Testing & Validation:**
Test the new feature by recording speeches that approach and exceed the 2-minute mark.
Ensure the transition to translation is smooth and that users don’t lose any recorded audio.

Acceptance Criteria:
The user receives a clear warning when their recording approaches the 2-minute limit.
Recordings that exceed 2 minutes are automatically translated without being lost, even if the user does not press the stop button.
No server errors occur when the time limit is exceeded.
The user interface shows a countdown and smoothly handles transitions from recording to translation.

@kaldan007 @tenkus47
